### ISSUE TITLE
Ability to report profile bio's / full accounts

### ISSUE THREAD

**Issue by thepluralassociation** [crabber-net/crabber#127] opened 2021-10-27 10:05 UTC
**Is your feature request related to a problem? Please describe.**
Some Crabbers have discovered that the text in bio can't be reported and stating ableist, dangerous or harmful things in there. I just reported a molt by them, hoping I could leave some feedback that the problem is in the bio of this account, but I wasn't able to report that.

**Describe the solution you'd like**
The ability to report a profile bio text and/or a full account. Because I assume once we can report the bio text, they will use the location or age tab etc. instead. 

**Describe alternatives you've considered**
When I click report a molt, it could show a popup that lets me click boxes on where the problem is with the account. (bio text, age text, location text, molts, etc.)  

**Additional context**
Thank you Jake!

**Comment by xpyxel** [comment] 2021-11-04 14:34
This seems to be a duplicate of #39 going to close it, feel free to reopen if you feel it isn't.

**Closed by xpyxel** 2021-11-04 14:34 UTC
Labels: enhancement, up-for-grabs
